name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Install awscli2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Upload
        run: |
          aws s3 cp \
            --recursive \
            --region ${{ env.AWS_REGION }} \
            ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_BUCKET }}
        env:
          NODE_ENV: development # optional: defaults to production
          AWS_S3_BUCKET: ${{ github.ref == 'refs/heads/master' && secrets.AWS_S3_BUCKET_DEV || github.ref == 'refs/heads/prod' && secrets.AWS_S3_BUCKET_PROD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1 # optional: defaults to us-east-1
          SOURCE_DIR: build # optional: defaults to public
      - name: Invalidate Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id \
            ${{ env.CLOUDFRONT_ID }} --paths "/*" --region us-east-1
        env:
          CLOUDFRONT_ID: ${{ github.ref == 'refs/heads/master' && secrets.AWS_CLOUDFRONT_DEV || github.ref == 'refs/heads/prod' && secrets.AWS_CLOUDFRONT_PROD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
